[versions]
agp = "9.0.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
# SDK Versions
compileSdk = "36"
minSdk = "21"
targetSdk = "36"
javaVersion = "22"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

[plugins]
application = { id = "com.android.application", version.ref = "agp" }
library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }